#!/usr/bin/env bash

set -eou pipefail

brew install \
    alacritty \
    stow

stow home-manager

nix doctor || sh <(curl -L https://nixos.org/nix/install)

nix-channel --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager

nix-channel --update

nix-shell '<home-manager>' -A install
