#!/usr/bin/env bash

set -eou pipefail

sudo apt update \
    && apt install -y \
        alacritty

sh <(curl -L https://nixos.org/nix/install) --daemon

nix run nixpkgs#home-manager -- switch --flake "$HOME/.dotfiles#$USER"
