#!/usr/bin/env bash

set -eou pipefail

sudo apt update \
    && apt install -y \
        stow \
        alacritty

stow home-manager

sh <(curl -L https://nixos.org/nix/install) --daemon

nix-channel --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager

nix-channel --update

nix-shell '<home-manager>' -A install
